version: '3'
name: pwn-cek-var-tapi-beda
services:
  cek-var-tapi-beda:
    image: cyb0x1/pwn-cek-var-tapi-beda:latest
    build: .
    restart: on-failure
    ports:
      - "9998:9998"
    # optional: add resource limit
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
    # optional: security settings
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=10m
