version: '3'
name: pwn-ret2win
services:
  ret2win:
    image: cyb0x1/pwn-ret2win:latest
    build: .
    restart: on-failure
    ports:
      - "9996:9996"
    # optional: add resource limit
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
    # optional: security settings
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=10m
