services:
  keycheck:
    build: .
    ports:
      - "11001:11001"
    restart: unless-stopped

    volumes:
      - ./flag.txt:/app/flag.txt:ro

    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
